# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Publications"
  url = "/publication/"
  weight = 20

[[main]]
  name = "Research"
  url = "/research/"
  weight = 30

[[main]]
  name = "Service"
  url = "/service/"
  weight = 35

[[main]]
  name = "Teaching"
  url = "/courses/"
  weight = 40

[[main]]
  name = "Talks"
  url = "/talk/"
  weight = 50

[[main]]
  name = "Hands-on"
  url = "/post/"
  weight = 60

[[lectures]]
  name = "Lectures"
  url = "/courses/ds4iot/lectures/"
  weight = 80

[[exam]]
  name = "Exam"
  url = "/courses/ds4iot/exam/"
  weight = 90

[[main]]
  name = "Visitors"
  url = "https://datastudio.google.com/s/iFJ0H_pp9bw"
  weight = 100

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 110

[[main]]
  name = "CV"
  url = "files/CV_academic_en.pdf"
  weight = 120
